# ============================================================================
# 📋 KEYWORDS DEL PERFIL DEL BEBÉ - ESPAÑOL
# ============================================================================

KEYWORDS_PROFILE_ES = {
    # ========================================================================
    # 💤 SUEÑO Y DESCANSO
    # ========================================================================
    "sleep and rest": {
        # 0-6 meses
        "0_6": {
        "sleep_rhythm": {
            "short_cycles": "ciclos cortos",
            "short_cycles": "ciclos de sueño cortos",
            "short_cycles": "sueños cortos",
            "long_night_block": "con bloque largo nocturno",
            "long_night_block": "bloque largo nocturno",
            "long_night_block": "duerme profundamente",
            "long_night_block": "duerme profundamente toda la noche",
            "long_night_block": "duerme profundamente en la noche",
            "long_night_block": "duerme toda la noche",
            "variable": "no siempre duerme igual",
            "variable": "duerme de forma distinta cada noche",
            "variable": "duerme de forma distinta todas las noches",
            "variable": "duerme de forma variable",
            "variable": "a veces duerme bien y a veces no",
        },
        "day_night_difference": {
            "does_not_distinguish": "no distingue dia de noche",
            "does_not_distinguish": "no distingue despertar ni acostarse",
            "does_not_distinguish": "no distingue el dia ni la noche",
            "does_not_distinguish": "no diferencia el dia de la noche",
            "does_not_distinguish": "no diferencia la hora de dormir con la hora de jugar",
            "does_not_distinguish": "no diferencia la hora de dormir con la de jugar",
            "starting_to_distinguish": "empieza a distinguir el día de la noche",
            "starting_to_distinguish": "empieza a distinguir la hora de dormir de la de jugar",
            "starting_to_distinguish": "empieza a diferenciar la hora de dormir de la de jugar",
            "starting_to_distinguish": "empieza a diferenciar la hora de dormir de la de jugar",
            "starting_to_distinguish": "empieza a diferenciar la hora de dormir de y la de jugar",
            "consolidated": "consolidado",
            "consolidated": "sabe distinguir el día de la noche",
            "consolidated": "sabe cuando hay que dormir y cuando hay que jugar",
            "consolidated": "sabe cuando hay que dormir y cuando es de día",
            "consolidated": "sabe cuando es de noche y cuando es de día",
        },
        "sleep_location": {
            "crib": "cuna",
            "co_sleeping": "colecho",
            "bassinet": "moisés",
            "in_motion": "duerme en movimiento",
            "in_motion": "se duerme en movimiento",
            "in_motion": "se queda dormido en movimiento",
        },
        "falling_asleep_support": {
            "breast": "duerme en mi pecho",
            "breast": "duerme encima de mi pecho",
            "breast": "duerme sobre mi pecho",
            "breast": "duerme sobre pecho",
            "in_arms": "duerme cuando lo tomo en brazos",
            "in_arms": "duerme cuando lo llevo en brazos",
            "in_arms": "duerme en mis brazos",
            "motion": "duerme en movimiento",
            "motion": "duerme solo si hay movimiento",
            "lullaby": "con un arrullo",
            "lullaby": "con un canto de arrullo",
            "lullaby": "con un canto",
            "lullaby": "con un canto suave",
            "lullaby": "con un canto tranquilo",
            "lullaby": "cantando su arrullo",
            "lullaby": "cantando algo",
            "eye_contact": "contacto visual",
            "eye_contact": "cuando hay contacto visual",
            "eye_contact": "cuando me mira a los ojos",
            "eye_contact": "cuando me mira a los ojos fijamente",
            "eye_contact": "cuando me mira",
        },
        "comfort_object": {
            "blankie": "mantita",
            "cloth": "tuto",
            "stuffed_animal": "su peluche",
            "stuffed_animal": "un peluche",
            "stuffed_animal": "el peluche",
            "doll": "su muñeca",
            "doll": "su muñeco",
            "doll": "la muñeca",
            "doll": "el muñeco",
            "doll": "el muñeco",
            "favorite_toy": "su juguete preferido",
            "favorite_toy": "su juguete favorito",
            "favorite_toy": "juguete favorito",
            "caregiver_clothing": "una prenda mia",
            "caregiver_clothing": "ropa mia",
            "caregiver_clothing": "prenda mia",
            "caregiver_clothing": "una prenda del cuidador",
            "caregiver_clothing": "ropa del cuidador",
            "small_pillow": "pequeña almohada",
            "small_pillow": "su almohada favorita",
            "small_pillow": "almohada pequeña",
            "small_pillow": "almohada chica",
            "small_pillow": "almohada chiquita",
            "small_pillow": "almohada chiquita",
            "pacifier": "su chupete",
            "pacifier": "su tete",
            "pacifier": "su chupón",
            "transitioning": "en transición de dejar su objeto de apego",
            "transitioning": "en transición a dejarlo",
            "transitioning": "en transición a dejar su objeto de apego",
            "transitioning": "en transición a dejarlo poco a poco",
            "other": "su objeto de apego",
            "other": "su objeto de apego favorito",
            "other": "su objeto favorito",
            "other": "su objeto de apego preferido",
            "other": "su objeto preferido",
            "none": "no tiene un objeto de apego definido por ahora",
            "none": "no tiene un objeto de apego definido",
            "none": "no tiene un objeto",
            "none": "no tiene objetivo de apego",
        },
        "naps_per_day": {
            "4": "4 siestas",
            "4": "cuatro siestas",
            "4": "hace 4 siestas",
            "4": "duerme 4 siestas",
            "4": "tiene 4 siestas",
            "5": "5 siestas",
            "5": "cinco siestas",
            "5": "hace 5 siestas",
            "5": "duerme 5 siestas",
            "5": "tiene 5 siestas",
            "6_or_more": "6 o más siestas",
            "6_or_more": "6 siestas",
            "6_or_more": "seis siestas",
            "6_or_more": "más de 6 siestas",
            "6_or_more": "muchas siestas",
            "6_or_more": "varias siestas al día",
            "6_or_more": "múltiples siestas",
        },
        "nap_duration": {
            "short": "siestas cortas",
            "short": "cortas",
            "short": "duerme siestas cortas",
            "short": "siestas breves",
            "short": "poco tiempo",
            "short": "ratitos cortos",
            "variable": "siestas variables",
            "variable": "variables",
            "variable": "a veces largas a veces cortas",
            "variable": "duración variable",
            "variable": "tiempo variable",
            "variable": "no siempre igual",
            "long": "siestas largas",
            "long": "largas",
            "long": "duerme siestas largas",
            "long": "mucho tiempo",
            "long": "bastante tiempo",
        },
        "wake_windows": {
            "min_30_45": "30–45 minutos",
            "min_30_45": "30-45 min",
            "min_30_45": "entre 30 y 45 minutos",
            "min_30_45": "media hora despierto",
            "min_30_45": "unos 30 minutos despierto",
            "min_30_45": "ventanas cortas",
            "min_45_60": "45–60 minutos",
            "min_45_60": "45-60 min",
            "min_45_60": "entre 45 y 60 minutos",
            "min_45_60": "casi una hora despierto",
            "min_45_60": "cerca de una hora despierto",
            "min_60_90": "60–90 minutos",
            "min_60_90": "60-90 min",
            "min_60_90": "entre 60 y 90 minutos",
            "min_60_90": "una hora despierto",
            "min_60_90": "hora y media despierto",
            "min_60_90": "aguanta una hora despierto",
        },
        "sleep_signals": {
            "staring": "mirada perdida",
            "staring": "tiene mirada perdida",
            "staring": "su mirada se pierde",
            "yawning": "bostezos",
            "yawning": "bosteza mucho",
            "slow_movements": "movimientos lentos",
            "slow_movements": "se mueve lento",
            "slow_movements": "se nota cansado",
            "slow_movements": "se ve cansado",
            "slow_movements": "movimientos torpes",
            "irritability": "irritabilidad",
            "irritability": "se irrita fácilmente",
            "irritability": "se irrita mucho",
            "irritability": "se irrita demasiado",
            "irritability": "se irrita con facilidad",
        },
        "main_sleep_association": {
            "breast": "le doy pecho",
            "breast": "con pecho",
            "bottle": "duerme con mamadera",
            "bottle": "con mamadera",
            "in_arms": "brazos",
            "motion": "movimiento",
            "lullaby": "arrullo",
        },
        "average_night_awakenings": {
            "2_3": "2–3 veces",
            "2_3": "2 o 3 veces",
            "2_3": "dos o tres veces",
            "2_3": "se despierta 2 o 3 veces",
            "2_3": "se levanta 2 o 3 veces",
            "2_3": "despierta 2 veces",
            "2_3": "despierta 3 veces",
            "4_5": "4–5 veces",
            "4_5": "4 o 5 veces",
            "4_5": "cuatro o cinco veces",
            "4_5": "se despierta 4 o 5 veces",
            "4_5": "se levanta 4 o 5 veces",
            "4_5": "despierta 4 veces",
            "4_5": "despierta 5 veces",
            "6_or_more": "6 o más veces",
            "6_or_more": "más de 6 veces",
            "6_or_more": "muchas veces",
            "6_or_more": "se despierta mucho",
            "6_or_more": "se despierta muy seguido",
            "6_or_more": "despierta constantemente",
            "6_or_more": "no duerme de corrido",
        },
        "back_to_sleep_method": {
            "breast": "pecho",
            "in_arms": "brazos",
            "contact": "contacto",
            "lullaby": "arrullo",
            "in_crib": "en cuna",
        },
        "sensory_profile": {
            "seeks_stimuli": "busca estímulos",
            "avoids_stimuli": "evita estímulos",
            "neutral": "neutro",
        },
        "calming_stimulus": {
            "motion": "movimiento",
            "deep_pressure": "presión profunda",
            "massage": "masaje",
            "white_noise": "ruido blanco",
            "contact": "contacto",
        },
        "sleepwear": {
            "base": {
                "short_sleeve_bodysuit": "con body de manga corta",
                "long_sleeve_bodysuit": "con body de manga larga",
                "undershirt_or_no_bodysuit": "con camiseta interior o sin body",
                "light_underwear_or_diaper": "solo con ropa interior o pañal",
            },
            "mid_layer": {
                "no_pajamas_bodysuit_only": "sin pijama, solo body",
                "one_piece_sleeper": "con pijama completo",
                "two_piece_pajamas": "con pijama de dos piezas",
                "thermal_or_fleece_pajamas": "con pijama térmico o polar",
                "nightgown_or_light_robe": "con camisón o bata ligera",
                "t_shirt_and_shorts": "con camiseta y short",
            },
            "cover_age_0_3": {
                "no_blanket_or_sleep_sack": "sin abrigo adicional",
                "sleep_sack_tog_0_5": "con saco liviano",
                "sleep_sack_tog_1_0": "con saco TOG",
                "sleep_sack_tog_1_5": "con saco TOG",
                "sleep_sack_tog_2_5": "con saco térmico",
                "light_blanket": "con una manta ligera",
                "thin_comforter": "con un cobertor delgado",
                "thick_comforter": "con un cobertor grueso",
                "other_cover": "con otro tipo de abrigo para dormir",
            },
            "cover_age_3_7": {
                "light_blanket": "con una manta ligera",
                "thin_comforter": "con un cobertor delgado",
                "thick_comforter": "con un cobertor grueso",
                "sheets": "con sábanas",
            },
        },
        "temperament": {
            "very_sensitive": "muy sensible",
            "adaptable": "adaptable",
            "active": "activo",
            "calm": "tranquilo",
        },
    },
    # ============================================================================
    # 💤 SUEÑO Y DESCANSO (6–12 MESES)
        "6_12": {
        "sleep_rhythm": {
            "frequent_awakenings": "con despertares frecuentes",
            "frequent_awakenings": "se despierta mucho",
            "frequent_awakenings": "se despierta seguido",
            "frequent_awakenings": "despierta muchas veces",
            "frequent_awakenings": "no duerme de corrido",
            "long_blocks": "con bloques largos",
            "long_blocks": "bloques largos de sueño",
            "long_blocks": "duerme periodos largos",
            "long_blocks": "duerme por periodos largos",
            "long_blocks": "duerme bastante seguido",
            "stable": "estable",
            "stable": "sueño estable",
            "stable": "ritmo estable",
            "stable": "duerme de forma estable",
            "stable": "duerme bien",
        },
        "day_night_difference": {
            "established": "establecida",
            "established": "bien establecida",
            "established": "ya distingue día y noche",
            "established": "sabe cuando es de día y de noche",
            "established": "diferencia día de noche",
            "in_adjustment": "aún en ajuste",
            "in_adjustment": "todavía en ajuste",
            "in_adjustment": "está ajustándose",
            "in_adjustment": "se está ajustando",
            "in_adjustment": "aún no del todo establecido",
        },
        "sleep_location": {
            "crib": "cuna",
            "crib": "en su cuna",
            "crib": "en la cuna",
            "crib": "duerme en cuna",
            "family_bed": "cama familiar",
            "family_bed": "en nuestra cama",
            "family_bed": "en la cama con nosotros",
            "family_bed": "duerme con nosotros",
            "partial_co_sleeping": "colecho parcial",
            "partial_co_sleeping": "a veces colecho",
            "partial_co_sleeping": "colecho algunas horas",
            "partial_co_sleeping": "parte de la noche con nosotros",
            "in_motion": "movimiento",
            "in_motion": "en movimiento",
            "in_motion": "duerme en movimiento",
            "in_motion": "solo durmiendo en movimiento",
        },
        "night_routine_established": {
            "yes": "si tenemos rutina",
            "yes": "tenemos rutina establecida",
            "yes": "rutina bien establecida",
            "yes": "ya tiene rutina",
            "partial": "a veces",
            "partial": "más o menos",
            "partial": "estamos trabajando en eso",
            "partial": "aún no del todo",
            "not_yet": "todavía no",
            "not_yet": "aún no tenemos",
            "not_yet": "sin rutina todavía",
            "not_yet": "no hemos establecido rutina",
        },
        "night_routine_elements": {
            "bath": "le damos un baño",
            "bath": "bañarlo",
            "bath": "la hora del baño",
            "massage": "masaje",
            "massage": "le damos masaje",
            "massage": "le hacemos masajes",
            "massage": "masajito",
            "story": "cuento",
            "story": "le leemos un cuento",
            "story": "lectura de cuento",
            "story": "contarle un cuento",
            "song": "canción",
            "song": "le cantamos",
            "song": "cantar canciones",
            "song": "canciones de cuna",
            "breast": "pecho",
            "breast": "le doy pecho",
            "breast": "toma pecho",
            "breast": "mamar",
            "lullaby": "arrullo",
            "lullaby": "lo arrullamos",
            "lullaby": "arrullarlo",
            "lullaby": "con arrullos",
        },
        "comfort_object": {
            "blankie": "mantita",
            "cloth": "tuto",
            "stuffed_animal": "su peluche",
            "doll": "su muñeca",
            "favorite_toy": "su juguete preferido",
            "caregiver_clothing": "una prenda tuya o del cuidador",
            "small_pillow": "una pequeña almohada",
            "pacifier": "su chupete",
            "transitioning": "en transición de dejar su objeto de apego",
            "other": "su objeto de apego",
            "none": "no tiene un objeto de apego definido por ahora",
        },
        "naps_per_day": {
            "1": "una siesta",
            "1": "1 siesta",
            "1": "hace una siesta",
            "1": "hace 1 siesta",
            "1": "duerme una siesta",
            "1": "duerme 1 siesta",
            "1": "tiene una siesta",
            "1": "solo una siesta",
            "1": "solamente una siesta",
            "1": "una sola siesta",
            "2": "dos siestas",
            "2": "2 siestas",
            "2": "hace dos siestas",
            "2": "hace 2 siestas",
            "2": "duerme dos siestas",
            "2": "duerme 2 siestas",
            "2": "tiene dos siestas",
            "2": "tiene 2 siestas",
            "2": "un par de siestas",
            "3": "tres siestas",
            "3": "3 siestas",
            "3": "hace tres siestas",
            "3": "hace 3 siestas",
            "3": "duerme tres siestas",
            "3": "duerme 3 siestas",
            "3": "tiene tres siestas",
            "3": "tiene 3 siestas",
            "4_or_more": "4 siestas",
            "4_or_more": "4 o más siestas",
            "4_or_more": "cuatro o más siestas",
            "4_or_more": "cuatro siestas",
            "4_or_more": "hace 4 siestas",
            "4_or_more": "hace cuatro siestas",
            "4_or_more": "duerme 4 siestas",
            "4_or_more": "duerme cuatro siestas",
            "4_or_more": "tiene 4 siestas",
            "4_or_more": "tiene cuatro siestas",
            "4_or_more": "más de 4 siestas",
            "4_or_more": "más de cuatro siestas",
            "4_or_more": "muchas siestas",
            "4_or_more": "varias siestas al día",
        },
        "nap_1_duration": {
            "less_30": "menos de treinta minutos",
            "less_30": "menos de treinta min",
            "less_30": "menos de 30 minutos",
            "less_30": "menos de 30 min",
            "less_30": "menos de media hora",
            "less_30": "duerme menos de 30 minutos",
            "less_30": "siestas cortas",
            "less_30": "siestas muy cortas",
            "less_30": "siestas de menos de media hora",
            "less_30": "no llega a los 30 minutos",
            "less_30": "unos 20 minutos",
            "less_30": "unos 15 minutos",
            "less_30": "siesta breve",
            "min_30_60": "entre treinta y sesenta minutos",
            "min_30_60": "entre treinta y 60 minutos",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "30 o 60 minutos",
            "min_30_60": "entre treinta y sesenta min",
            "min_30_60": "entre treinta y 60 min",
            "min_30_60": "entre 30 y 60 min",
            "min_30_60": "30 o 60 min",
            "min_30_60": "media hora aproximadamente",
            "min_30_60": "alrededor de media hora",
            "min_30_60": "unos 40 minutos",
            "min_30_60": "unos 45 minutos",
            "min_30_60": "entre media hora y una hora",
            "min_30_60": "de media hora a una hora",
            "min_30_60": "duerme entre 30 y 60 minutos",
            "min_30_60": "siesta de 30 a 60 minutos",
            "min_60_90": "entre sesenta y noventa minutos",
            "min_60_90": "entre sesenta y noventa min",
            "min_60_90": "entre 60 y 90 minutos",
            "min_60_90": "entre 60 y 90 min",
            "min_60_90": "entre 1 hora y 1 hora y 30 minutos",
            "min_60_90": "entre 1 hora y 1 hora y 30 min",
            "min_60_90": "entre 1 hora y 1 hora y media",
            "min_60_90": "una hora aproximadamente",
            "min_60_90": "alrededor de una hora",
            "min_60_90": "cerca de una hora",
            "min_60_90": "una hora y algo",
            "min_60_90": "una hora y pico",
            "min_60_90": "una hora y quince",
            "min_60_90": "unos 75 minutos",
            "min_60_90": "hora y media",
            "min_60_90": "duerme entre 60 y 90 minutos",
            "min_60_90": "siesta de una hora a hora y media",
            "more_90": "más de hora y media",
            "more_90": "más de 1 hora y 30 minutos",
            "more_90": "más de 1 hora y 30 min",
            "more_90": "más de 90 minutos",
            "more_90": "casi dos horas",
            "more_90": "dos horas",
            "more_90": "2 horas",
            "more_90": "más de 2 horas",
            "more_90": "siestas largas",
            "more_90": "siestas muy largas",
            "more_90": "duerme más de hora y media",
            "more_90": "siesta de más de hora y media",
            "more_90": "siesta de 2 horas",
            "more_90": "siesta larga",
        },
        "nap_2_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "menos de media hora",
            "less_30": "menos de treinta minutos",
            "less_30": "<30 min",
            "less_30": "segunda siesta corta",
            "less_30": "siesta 2 corta",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "media hora a una hora",
            "min_30_60": "segunda siesta media",
            "min_60_90": "1–1.5 horas",
            "min_60_90": "1-1.5 h",
            "min_60_90": "una hora a hora y media",
            "min_60_90": "entre 60 y 90 minutos",
            "min_60_90": "segunda siesta larga",
            "more_90": "más de 1.5 horas",
            "more_90": ">1.5 h",
            "more_90": "más de hora y media",
            "more_90": "casi 2 horas",
            "more_90": "2 horas la segunda siesta",
        },
        "nap_3_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "menos de media hora",
            "less_30": "<30 min",
            "less_30": "tercera siesta corta",
            "less_30": "siesta 3 corta",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "tercera siesta media",
            "min_60_90": "1–1.5 horas",
            "min_60_90": "1-1.5 h",
            "min_60_90": "una hora a hora y media",
            "min_60_90": "tercera siesta larga",
            "more_90": "más de 1.5 horas",
            "more_90": ">1.5 h",
            "more_90": "más de hora y media",
            "more_90": "tercera siesta muy larga",
        },
        "wake_windows": {
            "min_90_120": "1.5–2 horas",
            "min_90_120": "1.5-2 h",
            "min_90_120": "hora y media a 2 horas",
            "min_90_120": "entre 90 y 120 minutos",
            "min_90_120": "aguanta hora y media despierto",
            "min_90_120": "casi 2 horas despierto",
            "min_120_150": "2–2.5 horas",
            "min_120_150": "2-2.5 h",
            "min_120_150": "2 horas a 2 horas y media",
            "min_120_150": "entre 2 y 2.5 horas",
            "min_120_150": "aguanta 2 horas despierto",
            "min_150_180": "2.5–3 horas",
            "min_150_180": "2.5-3 h",
            "min_150_180": "2 horas y media a 3 horas",
            "min_150_180": "entre 2.5 y 3 horas",
            "min_150_180": "casi 3 horas despierto",
            "more_180": "más de 3 horas",
            "more_180": ">3 h",
            "more_180": "más de 3 horas despierto",
            "more_180": "aguanta más de 3 horas",
            "more_180": "ventanas largas",
        },
        "last_wake_window": {
            "short": "corta",
            "short": "última ventana corta",
            "short": "menos de 3 horas",
            "short": "<3 h",
            "short": "ventana corta antes de dormir",
            "medium": "media",
            "medium": "última ventana media",
            "medium": "3–4 horas",
            "medium": "3-4 h",
            "medium": "entre 3 y 4 horas",
            "long": "larga",
            "long": "última ventana larga",
            "long": "más de 4 horas",
            "long": ">4 h",
            "long": "ventana muy larga",
        },
        "main_sleep_association": {
            "breast": "pecho",
            "breast": "le doy pecho",
            "breast": "toma pecho",
            "breast": "se duerme con pecho",
            "breast": "necesita pecho para dormir",
            "in_arms": "brazos",
            "in_arms": "en mis brazos",
            "in_arms": "lo tengo en brazos",
            "in_arms": "se duerme en brazos",
            "in_arms": "necesita brazos",
            "motion": "movimiento",
            "motion": "con movimiento",
            "motion": "mecerlo",
            "motion": "meciéndolo",
            "motion": "necesita movimiento",
            "in_crib": "en cuna",
            "in_crib": "en su cuna",
            "in_crib": "se duerme en la cuna",
            "in_crib": "solito en la cuna",
            "contact": "contacto",
            "contact": "contacto físico",
            "contact": "necesita contacto",
            "contact": "tocándolo",
        },
        "average_night_awakenings": {
            "1_2": "1–2 veces",
            "1_2": "1 o 2 veces",
            "1_2": "una o dos veces",
            "1_2": "se despierta 1 vez",
            "1_2": "se despierta 2 veces",
            "1_2": "despierta una vez",
            "1_2": "despierta dos veces",
            "1_2": "pocas veces en la noche",
            "3_4": "3–4 veces",
            "3_4": "3 o 4 veces",
            "3_4": "tres o cuatro veces",
            "3_4": "se despierta 3 veces",
            "3_4": "se despierta 4 veces",
            "3_4": "despierta tres veces",
            "3_4": "despierta cuatro veces",
            "more_4": "más de 4 veces",
            "more_4": "más de cuatro veces",
            "more_4": "muchas veces",
            "more_4": "se despierta mucho",
            "more_4": "despierta constantemente",
            "more_4": "no duerme de corrido",
            "more_4": "despierta muy seguido",
        },
        "back_to_sleep_method": {
            "breast": "pecho",
            "breast": "le doy pecho",
            "breast": "toma pecho",
            "breast": "con pecho vuelve a dormir",
            "in_arms": "brazos",
            "in_arms": "en brazos",
            "in_arms": "lo tomo en brazos",
            "in_arms": "cargándolo",
            "comfort_object": "objeto de apego",
            "comfort_object": "su objeto",
            "comfort_object": "con su objeto de apego",
            "comfort_object": "le doy su objeto",
            "in_crib": "en cuna",
            "in_crib": "en la cuna",
            "in_crib": "solo en su cuna",
            "in_crib": "vuelve a dormir solo",
            "adult_voice": "voz del adulto",
            "adult_voice": "con mi voz",
            "adult_voice": "hablándole",
            "adult_voice": "solo hablándole",
        },
        "night_feeding_presence": {
            "yes": "toma leche en la noche",
            "yes": "sí toma leche",
            "yes": "come en la noche",
            "yes": "le doy leche de noche",
            "yes": "le doy pecho en la noche",
            "yes": "toma mamadera en la noche",
            "partial": "parcial",
            "partial": "a veces",
            "partial": "no siempre",
            "partial": "algunas noches",
            "no": "no toma leche en la noche",
            "no": "no toma leche al momento de dormir",
            "no": "no le doy leche antes de dormir",
            "no": "no le doy pecho",
            "no": "no le doy mamadera",
            "no": "ya no come de noche",
        },
        "sensory_profile": {
            "seeks_stimuli": "busca estímulos",
            "seeks_stimuli": "le gustan los estímulos",
            "seeks_stimuli": "necesita estímulos",
            "seeks_stimuli": "muy estimulado",
            "avoids_stimuli": "evita estímulos",
            "avoids_stimuli": "se sobre estimula",
            "avoids_stimuli": "sensible a estímulos",
            "avoids_stimuli": "rechaza estímulos",
            "balanced": "equilibrado",
            "balanced": "balance normal",
            "balanced": "ni mucho ni poco",
            "balanced": "normal",
        },
        "calming_stimulus": {
            "massage": "masaje",
            "massage": "masajes",
            "massage": "le hacemos masajes",
            "massage": "con masajitos",
            "soft_motion": "movimiento suave",
            "soft_motion": "movimiento lento",
            "soft_motion": "mecerlo suave",
            "soft_motion": "balanceo suave",
            "deep_pressure": "presión profunda",
            "deep_pressure": "presión",
            "deep_pressure": "apretarlo",
            "deep_pressure": "sostenerlo firme",
            "contact": "contacto",
            "contact": "contacto físico",
            "contact": "tocarlo",
            "contact": "estar en contacto",
            "lullaby": "arrullo",
            "lullaby": "arrullarlo",
            "lullaby": "con arrullos",
            "lullaby": "cantarle",
        },
        "room_temperature": {
            "recommended_range": "20–23 °C recomendado",
        },
        "room_humidity": {
            "recommended_range": "45–55 % recomendado",
        },
        "sleepwear": {
            "referenced_from": "al final del doc 0–6 meses",
        },
        "adult_accompaniment": {
            "constant_contact": "contacto físico constante",
            "constant_contact": "contacto todo el tiempo",
            "constant_contact": "siempre en contacto",
            "constant_contact": "necesita contacto constante",
            "close_presence": "presencia cercana",
            "close_presence": "cerca de él",
            "close_presence": "al lado",
            "close_presence": "presencia cerca",
            "from_distance": "desde distancia",
            "from_distance": "a distancia",
            "from_distance": "desde lejos",
            "from_distance": "sin estar tan cerca",
        },
        "temperament": {
            "sensitive": "sensible",
            "sensitive": "muy sensible",
            "sensitive": "bebé sensible",
            "sensitive": "delicado",
            "adaptable": "adaptable",
            "adaptable": "se adapta bien",
            "adaptable": "flexible",
            "adaptable": "fácil de adaptar",
            "active": "activo",
            "active": "muy activo",
            "active": "bebé activo",
            "active": "inquieto",
            "calm": "tranquilo",
            "calm": "calmado",
            "calm": "bebé tranquilo",
            "calm": "relajado",
        },
        "sleep_comments": {
            "notes": "comentarios o particularidades del sueño",
        },
    },
    # ============================================================================
    # 💤 SUEÑO Y DESCANSO (12–24 MESES)
        "12_24": {
        "sleep_rhythm": {
            "frequent_awakenings": "despertares frecuentes",
            "frequent_awakenings": "se despierta mucho",
            "frequent_awakenings": "muchos despertares",
            "frequent_awakenings": "no duerme seguido",
            "long_blocks": "bloques largos",
            "long_blocks": "bloques largos de sueño",
            "long_blocks": "duerme por bloques largos",
            "long_blocks": "periodos largos",
            "stable": "estable",
            "stable": "sueño estable",
            "stable": "duerme bien",
            "stable": "ritmo estable",
        },
        "sleep_location": {
            "crib": "cuna",
            "crib": "en su cuna",
            "crib": "en la cuna",
            "crib": "duerme en cuna",
            "family_bed": "cama familiar",
            "family_bed": "nuestra cama",
            "family_bed": "cama con nosotros",
            "family_bed": "duerme con nosotros",
            "partial_co_sleeping": "colecho parcial",
            "partial_co_sleeping": "a veces colecho",
            "partial_co_sleeping": "colecho parte de la noche",
            "own_bed": "su propia cama",
            "own_bed": "su cama",
            "own_bed": "en su camita",
            "own_bed": "tiene su cama",
            "in_motion": "movimiento",
            "in_motion": "en movimiento",
            "in_motion": "durmiendo en movimiento",
        },
        "night_routine_established": {
            "yes": "sí",
            "partial": "parcialmente",
            "not_yet": "no aún",
        },
        "night_routine_elements": {
            "bath": "baño",
            "massage": "masaje",
            "story": "cuento",
            "song": "canción",
            "breast": "pecho",
            "lullaby": "arrullo",
        },
        "comfort_object": {
            "blankie": "mantita",
            "cloth": "tuto",
            "stuffed_animal": "su peluche",
            "doll": "su muñeca",
            "favorite_toy": "su juguete preferido",
            "caregiver_clothing": "una prenda tuya o del cuidador",
            "small_pillow": "una pequeña almohada",
            "pacifier": "su chupete",
            "transitioning": "en transición de dejar su objeto de apego",
            "other": "su objeto de apego",
            "none": "no tiene un objeto de apego definido por ahora",
        },
        "naps_per_day": {
            "1": "1 siesta",
            "1": "una siesta",
            "1": "hace 1 siesta",
            "1": "hace una siesta",
            "1": "duerme 1 siesta",
            "1": "duerme una siesta",
            "1": "solo una siesta",
            "1": "una sola siesta",
            "2": "2 siestas",
            "2": "dos siestas",
            "2": "hace 2 siestas",
            "2": "hace dos siestas",
            "2": "duerme 2 siestas",
            "2": "duerme dos siestas",
            "2": "un par de siestas",
            "3": "3 siestas",
            "3": "tres siestas",
            "3": "hace 3 siestas",
            "3": "hace tres siestas",
            "3": "duerme 3 siestas",
            "3": "duerme tres siestas",
        },
        "nap_1_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "menos de media hora",
            "less_30": "<30 min",
            "less_30": "siesta corta",
            "less_30": "menos de treinta minutos",
            "less_30": "unos 20 minutos",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "media hora a una hora",
            "min_30_60": "unos 45 minutos",
            "min_30_60": "alrededor de una hora",
            "min_60_90": "1–1.5 horas",
            "min_60_90": "1-1.5 h",
            "min_60_90": "una hora a hora y media",
            "min_60_90": "entre 60 y 90 minutos",
            "min_60_90": "hora y media",
            "more_90": "más de 1.5 horas",
            "more_90": ">1.5 h",
            "more_90": "más de hora y media",
            "more_90": "casi 2 horas",
            "more_90": "2 horas",
            "more_90": "siesta larga",
        },
        "nap_2_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "menos de media hora",
            "less_30": "<30 min",
            "less_30": "segunda siesta corta",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "segunda siesta media",
            "min_60_90": "1–1.5 horas",
            "min_60_90": "1-1.5 h",
            "min_60_90": "segunda siesta larga",
            "more_90": "más de 1.5 horas",
            "more_90": ">1.5 h",
            "more_90": "segunda siesta muy larga",
        },
        "main_nap_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "<30 min",
            "less_30": "siesta principal corta",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "siesta principal media",
            "min_60_90": "1–1.5 horas",
            "min_60_90": "1-1.5 h",
            "min_60_90": "siesta principal larga",
            "more_90": "más de 1.5 horas",
            "more_90": ">1.5 h",
            "more_90": "siesta principal muy larga",
        },
        "wake_windows": {
            "min_120_150": "2–2.5 horas",
            "min_120_150": "2-2.5 h",
            "min_120_150": "2 horas a 2 horas y media",
            "min_120_150": "entre 2 y 2.5 horas",
            "min_120_150": "aguanta 2 horas despierto",
            "min_150_180": "2.5–3 horas",
            "min_150_180": "2.5-3 h",
            "min_150_180": "2 horas y media a 3 horas",
            "min_150_180": "entre 2.5 y 3 horas",
            "min_150_180": "casi 3 horas despierto",
            "min_180_240": "3–4 horas",
            "min_180_240": "3-4 h",
            "min_180_240": "3 a 4 horas",
            "min_180_240": "entre 3 y 4 horas",
            "min_180_240": "aguanta 3 o 4 horas despierto",
            "more_240": "más de 4 horas",
            "more_240": ">4 h",
            "more_240": "más de 4 horas despierto",
            "more_240": "aguanta mucho tiempo despierto",
            "more_240": "ventanas muy largas",
        },
        "last_wake_window": {
            "short": "corta",
            "short": "última ventana corta",
            "short": "menos de 3 horas",
            "short": "<3 h",
            "short": "poco tiempo antes de dormir",
            "medium": "media",
            "medium": "última ventana media",
            "medium": "3–4 horas",
            "medium": "3-4 h",
            "medium": "entre 3 y 4 horas antes de dormir",
            "long": "larga",
            "long": "última ventana larga",
            "long": "más de 4 horas",
            "long": ">4 h",
            "long": "mucho tiempo despierto antes de dormir",
        },
        "main_sleep_association": {
            "breast": "pecho",
            "breast": "con pecho",
            "breast": "toma pecho",
            "breast": "se duerme mamando",
            "in_arms": "brazos",
            "in_arms": "en brazos",
            "in_arms": "cargándolo",
            "in_arms": "se duerme en brazos",
            "motion": "movimiento",
            "motion": "con movimiento",
            "motion": "meciéndolo",
            "motion": "necesita movimiento",
            "in_crib": "en cuna",
            "in_crib": "en su cuna",
            "in_crib": "solito en cuna",
            "contact": "contacto",
            "contact": "contacto físico",
            "contact": "tocándolo",
        },
        "night_feeding_presence": {
            "yes": "toma leche en la noche",
            "partial": "parcial",
            "no": "no toma leche en la noche",
            "no": "no toma leche al momento de dormir",
            "no": "no le doy leche antes de dormir",
            "no": "no le doy pecho",
            "no": "no le doy mamadera",
        },
        "night_weaning_process": {
            "in_progress": "en proceso de destete nocturno",
            "in_progress": "estamos en proceso",
            "in_progress": "dejando tomas nocturnas",
            "in_progress": "quitando tomas de noche",
            "completed": "destete nocturno completado",
            "completed": "ya no toma de noche",
            "completed": "destete completo",
            "completed": "terminado",
            "not_started": "aún no iniciado",
            "not_started": "no hemos empezado",
            "not_started": "todavía no",
            "not_started": "sin empezar",
        },
        "back_to_sleep_method": {
            "breast": "pecho",
            "breast": "le doy pecho",
            "breast": "con pecho",
            "in_arms": "brazos",
            "in_arms": "en brazos",
            "in_arms": "cargándolo",
            "comfort_object": "objeto de apego",
            "comfort_object": "su objeto",
            "comfort_object": "le doy su objeto",
            "in_crib": "en cuna",
            "in_crib": "en la cuna",
            "in_crib": "vuelve a dormir solo",
            "adult_voice": "voz del adulto",
            "adult_voice": "con mi voz",
            "adult_voice": "hablándole",
        },
        "night_accompaniment": {
            "constant_contact": "contacto físico constante",
            "constant_contact": "contacto todo el tiempo",
            "constant_contact": "siempre tocándolo",
            "close_presence": "presencia cercana",
            "close_presence": "cerca de él",
            "close_presence": "a su lado",
            "from_distance": "desde distancia",
            "from_distance": "a distancia",
            "from_distance": "desde lejos",
        },
        "sensory_profile": {
            "seeks_stimuli": "busca estímulos",
            "avoids_stimuli": "evita estímulos",
            "balanced": "equilibrado",
        },
        "calming_stimulus": {
            "massage": "masaje",
            "soft_motion": "movimiento suave",
            "deep_pressure": "presión profunda",
            "contact": "contacto",
            "lullaby": "arrullo",
        },
        "room_temperature": {
            "recommended_range": "20–23 °C recomendado",
        },
        "room_humidity": {
            "recommended_range": "45–55 % recomendado",
        },
        "sleepwear": {
            "referenced_from": "al final del doc 0–6 meses",
        },
        "temperament": {
            "sensitive": "sensible",
            "adaptable": "adaptable",
            "active": "activo",
            "calm": "tranquilo",
        },
        "sleep_comments": {
            "notes": "comentarios o particularidades del sueño",
        },
    },
    # ============================================================================
    # 💤 SUEÑO Y DESCANSO (24–48 MESES)
        "24_48": {
        "sleep_rhythm": {
            "stable": "estable",
            "stable": "sueño estable",
            "stable": "duerme bien",
            "stable": "ritmo estable",
            "stable": "consistente",
            "occasional_awakenings": "con despertares ocasionales",
            "occasional_awakenings": "a veces se despierta",
            "occasional_awakenings": "despertares ocasionales",
            "occasional_awakenings": "de vez en cuando despierta",
            "frequent_awakenings": "con despertares frecuentes",
            "frequent_awakenings": "se despierta mucho",
            "frequent_awakenings": "despertares frecuentes",
            "frequent_awakenings": "no duerme seguido",
        },
        "sleep_location": {
            "low_bed": "cama baja",
            "low_bed": "su cama baja",
            "low_bed": "camita baja",
            "low_bed": "cama al ras del suelo",
            "crib": "cuna",
            "crib": "en su cuna",
            "crib": "todavía en cuna",
            "family_bed": "cama familiar",
            "family_bed": "nuestra cama",
            "family_bed": "duerme con nosotros",
            "transition_room": "transición a su habitación",
            "transition_room": "pasando a su cuarto",
            "transition_room": "en transición",
            "transition_room": "empezando en su pieza",
        },
        "night_routine_established": {
            "yes": "sí",
            "yes": "si tenemos rutina",
            "yes": "rutina establecida",
            "yes": "ya tiene rutina",
            "partial": "parcialmente",
            "partial": "a veces",
            "partial": "más o menos",
            "partial": "no siempre",
            "no": "no",
            "no": "no tenemos rutina",
            "no": "sin rutina",
            "no": "aún no",
        },
        "night_routine_elements": {
            "bath": "baño",
            "bath": "le damos baño",
            "bath": "bañarlo",
            "brushing": "cepillado",
            "brushing": "lavar dientes",
            "brushing": "cepillar dientes",
            "brushing": "lavarse los dientes",
            "story": "cuento",
            "story": "lectura",
            "story": "leer un cuento",
            "story": "contarle un cuento",
            "song": "canción",
            "song": "cantarle",
            "song": "canciones",
            "hug": "abrazo",
            "hug": "abrazarlo",
            "hug": "abrazos",
            "hug": "abrazo de buenas noches",
            "comfort_object": "objeto de apego",
            "comfort_object": "su objeto",
            "comfort_object": "darle su objeto",
        },
        "comfort_object": {
            "blankie": "mantita",
            "cloth": "tuto",
            "stuffed_animal": "su peluche",
            "doll": "su muñeca",
            "favorite_toy": "su juguete preferido",
            "caregiver_clothing": "una prenda tuya o del cuidador",
            "small_pillow": "una pequeña almohada",
            "pacifier": "su chupete",
            "transitioning": "en transición de dejar su objeto de apego",
            "other": "su objeto de apego",
            "none": "no tiene un objeto de apego definido por ahora",
        },
        "naps_per_day": {
            "0": "0 siestas",
            "0": "no duerme siesta",
            "0": "ya no hace siesta",
            "0": "sin siesta",
            "0": "ninguna siesta",
            "1": "1 siesta",
            "1": "una siesta",
            "1": "hace 1 siesta",
            "1": "hace una siesta",
            "1": "duerme 1 siesta",
            "1": "duerme una siesta",
            "1": "solo una siesta",
            "2_occasional": "2 siestas ocasionales",
            "2_occasional": "2 (ocasionales)",
            "2_occasional": "a veces 2 siestas",
            "2_occasional": "ocasionalmente 2 siestas",
            "2_occasional": "dos siestas de vez en cuando",
        },
        "nap_duration": {
            "less_45": "menos de 45 minutos",
            "less_45": "<45 min",
            "less_45": "menos de tres cuartos de hora",
            "less_45": "siesta corta",
            "less_45": "menos de 45 min",
            "min_45_90": "45–90 minutos",
            "min_45_90": "45-90 min",
            "min_45_90": "entre 45 y 90 minutos",
            "min_45_90": "una hora aproximadamente",
            "min_45_90": "hora y algo",
            "more_90": "más de 90 minutos",
            "more_90": ">90 min",
            "more_90": "más de hora y media",
            "more_90": "siesta larga",
            "more_90": "casi 2 horas",
        },
        "nap_need": {
            "daily": "siesta diaria",
            "daily": "todos los días",
            "daily": "necesita siesta todos los días",
            "daily": "duerme siesta a diario",
            "occasional": "siesta ocasional",
            "occasional": "a veces",
            "occasional": "de vez en cuando",
            "occasional": "algunos días",
            "no_nap": "ya no duerme siesta",
            "no_nap": "sin siesta",
            "no_nap": "no hace siesta",
            "no_nap": "dejó la siesta",
        },
        "wake_windows": {
            "min_240_300": "4–5 horas",
            "min_240_300": "4-5 h",
            "min_240_300": "entre 4 y 5 horas",
            "min_240_300": "cuatro a cinco horas",
            "min_240_300": "aguanta 4 horas despierto",
            "min_240_300": "aguanta 5 horas despierto",
            "min_300_360": "5–6 horas",
            "min_300_360": "5-6 h",
            "min_300_360": "entre 5 y 6 horas",
            "min_300_360": "cinco a seis horas",
            "min_300_360": "aguanta 5 o 6 horas despierto",
            "more_360": "más de 6 horas",
            "more_360": ">6 h",
            "more_360": "más de 6 horas despierto",
            "more_360": "aguanta mucho tiempo despierto",
            "more_360": "todo el día despierto",
        },
        "last_wake_window": {
            "short": "corta",
            "short": "última ventana corta",
            "short": "menos de 5 horas",
            "short": "<5 h",
            "medium": "media",
            "medium": "última ventana media",
            "medium": "5–6 horas",
            "medium": "5-6 h",
            "medium": "entre 5 y 6 horas",
            "long": "larga",
            "long": "última ventana larga",
            "long": "más de 6 horas",
            "long": ">6 h",
        },
        "main_sleep_association": {
            "contact": "contacto",
            "contact": "contacto físico",
            "contact": "tocándolo",
            "contact": "necesita contacto",
            "comfort_object": "objeto de apego",
            "comfort_object": "su objeto",
            "comfort_object": "con su objeto",
            "story_or_song": "cuento o canción",
            "story_or_song": "con cuento",
            "story_or_song": "con canción",
            "story_or_song": "leyéndole",
            "by_self": "por sí mismo",
            "by_self": "solito",
            "by_self": "se duerme solo",
            "by_self": "solo",
        },
        "night_feeding_presence": {
           "yes": "toma leche en la noche",
            "partial": "parcial",
            "no": "no toma leche en la noche",
            "no": "no toma leche al momento de dormir",
            "no": "no le doy leche antes de dormir",
            "no": "no le doy pecho",
            "no": "no le doy mamadera",
        },
        "night_feeding_frequency": {
            "once": "1 vez",
            "once": "una vez",
            "once": "solo una vez",
            "once": "come una vez",
            "two_three": "2–3 veces",
            "two_three": "2 o 3 veces",
            "two_three": "dos o tres veces",
            "more_three": "más de 3",
            "more_three": "más de 3 veces",
            "more_three": "muchas veces",
            "variable": "variable según enfermedad o apego",
            "variable": "variable",
            "variable": "depende",
            "variable": "no siempre igual",
        },
        "night_feeding_reason": {
            "hunger": "hambre",
            "hunger": "tiene hambre",
            "hunger": "por hambre",
            "comfort": "consuelo",
            "comfort": "para consolarse",
            "comfort": "busca consuelo",
            "habit": "hábito",
            "habit": "por hábito",
            "habit": "costumbre",
            "bonding": "vínculo",
            "bonding": "por apego",
            "bonding": "conexión",
            "unknown": "no identificado",
            "unknown": "no sé",
            "unknown": "no estoy seguro",
        },
        "night_weaning_process": {
            "not_started": "no iniciado",
            "not_started": "no hemos empezado",
            "not_started": "aún no",
            "in_progress": "en proceso",
            "in_progress": "estamos en eso",
            "in_progress": "trabajando en ello",
            "completed": "finalizado",
            "completed": "terminado",
            "completed": "ya no come de noche",
        },
        "night_awakenings": {
            "none": "no",
            "none": "no se despierta",
            "none": "duerme toda la noche",
            "occasional": "ocasional",
            "occasional": "a veces",
            "occasional": "1–2 veces",
            "occasional": "de vez en cuando",
            "frequent": "frecuentes",
            "frequent": "se despierta mucho",
            "frequent": "más de 2 veces",
            "frequent": ">2",
        },
        "night_accompaniment": {
            "breast": "pecho",
            "breast": "le doy pecho",
            "breast": "con pecho",
            "physical_contact": "contacto físico",
            "physical_contact": "tocándolo",
            "physical_contact": "con contacto",
            "voice": "voz",
            "voice": "con mi voz",
            "voice": "hablándole",
            "calm_presence": "presencia tranquila",
            "calm_presence": "estando cerca",
            "calm_presence": "mi presencia",
            "return_to_bed": "invita a volver a su cama",
            "return_to_bed": "lo llevo a su cama",
            "return_to_bed": "vuelve a su cama",
        },
        "night_fears_presence": {
            "none": "no",
            "none": "no tiene miedos",
            "none": "sin miedos",
            "darkness": "a la oscuridad",
            "darkness": "oscuridad",
            "darkness": "le tiene miedo a la oscuridad",
            "separation": "a separarse",
            "separation": "separación",
            "separation": "miedo a estar solo",
            "noises": "a ruidos",
            "noises": "ruidos",
            "noises": "sonidos",
            "other": "otros",
            "other": "otros miedos",
        },
        "night_fears_reaction": {
            "seeks_contact": "busca contacto",
            "seeks_contact": "me busca",
            "seeks_contact": "quiere que lo toque",
            "asks_for_light": "pide luz",
            "asks_for_light": "quiere luz",
            "asks_for_light": "pide que prenda la luz",
            "calls": "llama",
            "calls": "me llama",
            "calls": "grita",
            "cries": "llora",
            "cries": "se pone a llorar",
            "gets_up": "se levanta",
            "gets_up": "sale de la cama",
            "gets_up": "viene a buscarnos",
        },
        "sensory_profile": {
            "seeks_stimuli": "busca estímulos",
            "avoids_stimuli": "evita estímulos",
            "balanced": "equilibrado",
        },
        "calming_stimulus": {
            "massage": "masaje",
            "quiet_reading": "lectura tranquila",
            "soft_music": "música suave",
            "contact": "contacto",
        },
        "room_temperature": {
            "recommended_range": "20–23 °C recomendado",
        },
        "room_humidity": {
            "recommended_range": "45–55 % recomendado",
        },
        "sleepwear": {
            "referenced_from": "al final del doc 0–6 meses",
        },
        "temperament": {
            "sensitive": "sensible",
            "adaptable": "adaptable",
            "active": "activo",
            "calm": "tranquilo",
            "persistent": "persistente",
        },
    },
    # ============================================================================
    # 💤 SUEÑO Y DESCANSO (48–84 MESES)
        "48_84": {
        "sleep_rhythm": {
            "stable": "estable",
            "stable": "sueño estable",
            "stable": "duerme bien",
            "stable": "consistente",
            "occasional_awakenings": "con despertares ocasionales",
            "occasional_awakenings": "a veces despierta",
            "occasional_awakenings": "despertares ocasionales",
            "frequent_awakenings": "con despertares frecuentes",
            "frequent_awakenings": "se despierta mucho",
            "frequent_awakenings": "muchos despertares",
        },
        "average_sleep_schedule": {
            "20_7": "duerme entre 20:00–7:00",
            "20_7": "duerme entre las 8 y las 7",
            "20_7": "de 8 de la noche a 7 de la mañana",
            "21_7": "duerme entre 21:00–7:00",
            "21_7": "duerme entre las 9 y las 7",
            "21_7": "de 9 de la noche a 7 de la mañana",
            "21_8": "duerme entre 21:00–8:00",
            "21_8": "duerme entre las 9 y las 8",
            "21_8": "de 9 de la noche a 8 de la mañana",
            "variable": "variable",
            "variable": "cambia",
            "variable": "no siempre igual",
            "variable": "depende del día",
        },
        "sleep_location": {
            "own_bed": "cama propia",
            "own_bed": "su cama",
            "own_bed": "en su cama",
            "own_bed": "tiene su cama",
            "shared_room": "habitación compartida",
            "shared_room": "comparte cuarto",
            "shared_room": "cuarto compartido",
            "family_bed": "cama familiar",
            "family_bed": "nuestra cama",
            "family_bed": "duerme con nosotros",
            "transition_room": "transición a su cuarto",
            "transition_room": "pasando a su pieza",
            "transition_room": "en transición",
        },
        "night_routine_established": {
            "yes": "sí",
            "partial": "parcialmente",
            "no": "no",
        },
        "night_routine_elements": {
            "bath": "baño",
            "brushing": "cepillado",
            "story": "cuento",
            "song": "canción",
            "hug": "abrazo",
            "day_talk": "diálogo sobre el día",
        },
        "comfort_object": {
            "blankie": "mantita",
            "cloth": "tuto",
            "stuffed_animal": "su peluche",
            "doll": "su muñeca",
            "favorite_toy": "su juguete preferido",
            "caregiver_clothing": "una prenda tuya o del cuidador",
            "small_pillow": "una pequeña almohada",
            "pacifier": "su chupete",
            "transitioning": "en transición de dejar su objeto de apego",
            "other": "su objeto de apego",
            "none": "no tiene un objeto de apego definido por ahora",
        },
        "nap_presence": {
            "no": "no duerme siesta",
            "no": "sin siesta",
            "no": "ya no hace siesta",
            "no": "no",
            "no": "ninguna siesta",
            "occasional": "siesta ocasional",
            "occasional": "a veces",
            "occasional": "de vez en cuando",
            "occasional": "ocasionalmente",
            "occasional": "algunos días",
            "daily": "siesta diaria",
            "daily": "todos los días",
            "daily": "a diario",
            "daily": "duerme siesta cada día",
        },
        "nap_duration": {
            "less_30": "menos de 30 minutos",
            "less_30": "<30 min",
            "less_30": "menos de media hora",
            "less_30": "siesta corta",
            "less_30": "menos de treinta minutos",
            "min_30_60": "30–60 minutos",
            "min_30_60": "30-60 min",
            "min_30_60": "entre 30 y 60 minutos",
            "min_30_60": "media hora a una hora",
            "min_30_60": "unos 45 minutos",
            "more_60": "más de 60 minutos",
            "more_60": ">60 min",
            "more_60": "más de una hora",
            "more_60": "siesta larga",
            "more_60": "hora y media o más",
        },
        "bedtime": {
            "before_20": "antes de las 20:00",
            "before_20": "antes de las 8",
            "before_20": "antes de las 8 de la noche",
            "before_20": "temprano",
            "before_20": "antes de las ocho",
            "20_21": "20:00–21:00",
            "20_21": "entre las 8 y las 9",
            "20_21": "entre las 20 y las 21",
            "20_21": "a las 8 de la noche",
            "20_21": "sobre las 8 o 9",
            "21_22": "21:00–22:00",
            "21_22": "entre las 9 y las 10",
            "21_22": "entre las 21 y las 22",
            "21_22": "a las 9 de la noche",
            "21_22": "sobre las 9 o 10",
            "after_22": "después de las 22:00",
            "after_22": "después de las 10",
            "after_22": "tarde",
            "after_22": "pasadas las 10",
            "after_22": "muy tarde",
        },
        "time_to_fall_asleep": {
            "less_15": "menos de 15 minutos",
            "less_15": "<15 min",
            "less_15": "se duerme rápido",
            "less_15": "rápidamente",
            "less_15": "en pocos minutos",
            "min_15_30": "15–30 minutos",
            "min_15_30": "15-30 min",
            "min_15_30": "entre 15 y 30 minutos",
            "min_15_30": "como 20 minutos",
            "min_15_30": "unos 20 o 30 minutos",
            "more_30": "más de 30 minutos",
            "more_30": ">30 min",
            "more_30": "tarda en dormirse",
            "more_30": "cuesta que se duerma",
            "more_30": "demora mucho",
        },
        "night_awakenings": {
            "none": "no",
            "none": "no se despierta",
            "none": "duerme toda la noche",
            "none": "sin despertares",
            "occasional": "ocasional",
            "occasional": "a veces",
            "occasional": "1–2 veces",
            "occasional": "de vez en cuando",
            "frequent": "frecuentes",
            "frequent": "se despierta mucho",
            "frequent": "más de 2 veces",
            "frequent": ">2",
        },
        "night_accompaniment": {
            "presence": "presencia",
            "presence": "mi presencia",
            "presence": "estando cerca",
            "voice": "voz",
            "voice": "con mi voz",
            "voice": "hablándole",
            "contact": "contacto",
            "contact": "contacto físico",
            "contact": "tocándolo",
            "falls_asleep_alone": "vuelve solo a dormir",
            "falls_asleep_alone": "se duerme solo",
            "falls_asleep_alone": "solito",
            "asks_for_adult": "pide al adulto",
            "asks_for_adult": "me llama",
            "asks_for_adult": "nos busca",
        },
        "sleep_autonomy": {
            "sleeps_alone": "se duerme solo",
            "sleeps_alone": "solo",
            "sleeps_alone": "solito",
            "sleeps_alone": "duerme sin ayuda",
            "with_support": "con acompañamiento",
            "with_support": "con ayuda",
            "with_support": "necesita compañía",
            "needs_constant_presence": "necesita presencia constante",
            "needs_constant_presence": "necesita que esté con él",
            "needs_constant_presence": "no duerme solo",
        },
        "night_fears_presence": {
            "none": "no",
            "none": "no tiene miedos",
            "none": "sin miedos",
            "darkness": "oscuridad",
            "darkness": "a la oscuridad",
            "darkness": "miedo a lo oscuro",
            "separation": "separación",
            "separation": "a separarse",
            "separation": "miedo a estar solo",
            "noises": "ruidos",
            "noises": "a los ruidos",
            "noises": "sonidos",
            "nightmares": "pesadillas",
            "nightmares": "tiene pesadillas",
            "nightmares": "sueños feos",
            "other": "otros",
            "other": "otros miedos",
        },
        "nightmare_frequency": {
            "none": "no",
            "none": "no tiene pesadillas",
            "none": "sin pesadillas",
            "occasional": "ocasional",
            "occasional": "a veces",
            "occasional": "de vez en cuando",
            "frequent": "frecuente",
            "frequent": "seguido",
            "frequent": "semanal",
            "frequent": "todas las semanas",
        },
        "nightmare_support": {
            "verbal_comfort": "consuelo verbal",
            "verbal_comfort": "hablándole",
            "verbal_comfort": "con palabras",
            "physical_contact": "contacto físico",
            "physical_contact": "abrazándolo",
            "physical_contact": "tocándolo",
            "dialogue": "diálogo",
            "dialogue": "conversando",
            "dialogue": "hablamos de eso",
            "returns_to_bed": "regresa a su cama",
            "returns_to_bed": "vuelve a su cama",
            "returns_to_bed": "lo llevo a su cama",
            "sleeps_with_adult": "duerme con adulto",
            "sleeps_with_adult": "duerme con nosotros",
            "sleeps_with_adult": "se queda en nuestra cama",
        },
        "sensory_profile": {
            "seeks_stimuli": "busca estímulos",
            "avoids_stimuli": "evita estímulos",
            "balanced": "equilibrado",
        },
        "calming_stimulus": {
            "quiet_reading": "lectura tranquila",
            "massage": "masaje",
            "breathing": "respiración",
            "music": "música",
            "guided_imagery": "visualización o cuento guiado",
        },
        "room_temperature": {
            "recommended_range": "20–23 °C recomendado",
        },
        "room_humidity": {
            "recommended_range": "45–55 % recomendado",
        },
        "sleepwear": {
            "referenced_from": "al final del doc 0–6 meses",
        },
        "temperament": {
            "sensitive": "sensible",
            "adaptable": "adaptable",
            "active": "activo",
            "calm": "tranquilo",
            "persistent": "persistente",
        },
        "sleep_comments": {
            "notes": "comentarios o particularidades del sueño",
        },
        },  # Fin 48_84
    },  # Fin sueño_y_descanso

    # ========================================================================
    # 🛁 CUIDADOS DIARIOS
    # ========================================================================
    "daily care": {
        # TODO: Por implementar
    },

    # ========================================================================
    # 🧩 AUTONOMÍA Y DESARROLLO INTEGRAL
    # ========================================================================
    "autonomy and development": {
        # TODO: Por implementar
    },
    
    # ========================================================================
    # ❤️ EMOCIONES, VÍNCULOS Y CRIANZA RESPETUOSA
    # ========================================================================
    "emotions bonds and parenting": {
        # TODO: Por implementar
    },
    
    # ========================================================================
    # 🏠 CONTEXTO FAMILIAR Y ENTORNO
    # ========================================================================
    "family context and environment": {
        # TODO: Por implementar
    },
    
    # ========================================================================
    # ✈️ VIAJES Y DESPLAZAMIENTOS
    # ========================================================================
    "travel and mobility": {
        # TODO: Por implementar
    },
}
