KEYWORDS_FAMILY_CONTEXT_EN = {
    "family context and environment": {
        "0_84": {
            "family_members": {
                "mother": [
                    "lives with mom",
                    "lives with mommy",
                    "lives with his mother",
                    "lives with her mother",
                ],
                "father": [
                    "lives with dad",
                    "lives with daddy",
                    "lives with his father",
                    "lives with her father",
                ],
                "both_parents": [
                    "lives with both parents",
                    "lives with mom and dad",
                ],
                "brothers": [
                    "lives with his brothers",
                    "lives with his sisters",
                    "lives with his brother",
                    "lives with his sister",
                    "has brothers",
                    "has sisters",
                    "has a brother",
                    "has a sister",
                ],
                "grandparents": [
                    "lives with his grandparents",
                    "lives with his grandfather",
                    "lives with his grandmother",
                    "has grandparents",
                    "has a grandfather",
                    "has a grandmother",
                    "lives with grandparents",
                ],
                "others_family_members": [
                    "lives with uncles",
                    "lives with aunts",
                    "lives with his uncle",
                    "lives with his aunt",
                    "lives with cousins",
                    "lives with his cousin",
                    "lives with relatives",
                    "lives with other family members",
                ],
                "caregivers": [
                    "lives with caregiver",
                    "lives with nanny",
                    "has a caregiver",
                    "has a nanny",
                ],
                "others": [
                    "lives with other people",
                    "lives with someone else",
                    "lives with another person",
                ],
            },
            "more_than_one_home": {
                "different_homes": [
                    "more than one house",
                    "several houses",
                    "different homes",
                    "different households",
                    "mom and dad's houses",
                    "lives in two homes",
                    "sometimes with mom",
                    "sometimes with dad",
                ],
                "One_home": [
                    "only one house",
                    "one home",
                    "single household",
                    "lives in one home",
                    "lives with his parents",
                    "lives with mom and dad",
                    "stable home",
                    "unique home",
                    "single home",
                    "lives with both parents",
                    "lives with mom and dad together",
                ],
            },
            "home_schedule": {
                "fixed_days": [
                    "fixed days",
                    "set days",
                ],
                "altern_weekends": [
                    "alternate weekends",
                    "rotating weekends",
                    "different weekends",
                    "one weekend with mom and one with dad",
                    "one weekend with dad and one with mom",
                    "weekends with each parent",
                    "weekends with both separately",
                ],
                "weekly_rotations": [
                    "weekly rotation",
                    "alternate weeks",
                    "different weeks",
                    "changing weeks",
                    "one week with mom and another with dad",
                    "one week with dad and another with mom",
                    "weeks with each parent",
                    "weeks with both alternately",
                ],
                "other_schedule": [
                    "other type of schedule",
                    "different schedule",
                ],
            },
            "principal_caregiver": {
                "mother": [
                    "mother is the main caregiver",
                    "mom is the main caregiver",
                    "mother takes care of the baby",
                    "mom takes care of the baby",
                    "mother is responsible for the child’s care",
                ],
                "father": [
                    "father is the main caregiver",
                    "dad is the main caregiver",
                    "father takes care of the baby",
                    "dad takes care of the baby",
                    "father is responsible for the child’s care",
                ],
                "both_parents": [
                    "both parents are the main caregivers",
                    "mom and dad are the main caregivers",
                    "both parents take care of the baby",
                    "parents share the child’s care",
                ],
                "granny_and_grandpa": [
                    "grandparents are the main caregivers",
                    "grandparents take care of the baby",
                    "grandparents care for the child",
                ],
                "granny": [
                    "grandmother is the main caregiver",
                    "grandma takes care of the baby",
                    "grandmother takes care of the child",
                ],
                "grandpa": [
                    "grandfather is the main caregiver",
                    "grandpa takes care of the baby",
                    "grandfather takes care of the child",
                ],
                "caregiver": [
                    "caregiver is the main caregiver",
                    "the caregiver takes care of the baby",
                    "caregiver looks after the child",
                ],
            },
            "go_to_daycare": {
                "no": [
                    "does not go to daycare",
                    "does not attend daycare",
                    "is not in daycare",
                    "does not go to kindergarten",
                    "does not attend kindergarten",
                    "is not in kindergarten",
                    "does not go to nursery school",
                    "does not attend nursery school",
                    "is not in nursery school",
                ],
                "kindergarden": [
                    "goes to daycare",
                    "attends daycare",
                    "is in daycare",
                    "goes to kindergarten",
                    "attends kindergarten",
                    "is in kindergarten",
                    "goes to nursery school",
                    "attends nursery school",
                    "is in nursery school",
                ],
                "school": [
                    "goes to school",
                    "attends school",
                    "is in school",
                    "goes to elementary school",
                    "attends elementary school",
                    "is in elementary school",
                ],
            },
            "days_of_attendance": {
                "monday": [
                    "monday at daycare",
                    "attends on mondays",
                    "goes on mondays",
                ],
                "tuesday": [
                    "tuesday at daycare",
                    "attends on tuesdays",
                    "goes on tuesdays",
                ],
                "wednesday": [
                    "wednesday at daycare",
                    "attends on wednesdays",
                    "goes on wednesdays",
                ],
                "thursday": [
                    "thursday at daycare",
                    "attends on thursdays",
                    "goes on thursdays",
                ],
                "friday": [
                    "friday at daycare",
                    "attends on fridays",
                    "goes on fridays",
                ],
            },
            "attendance_schedule": {
                "morning": [
                    "attends in the morning",
                    "goes in the morning",
                    "morning schedule",
                    "morning session",
                ],
                "afternoon": [
                    "attends in the afternoon",
                    "goes in the afternoon",
                    "afternoon schedule",
                    "afternoon session",
                ],
                "full_day": [
                    "attends all day",
                    "goes all day",
                    "full-day schedule",
                    "full-time attendance",
                ],
            },
            "entry_time": {
                "early_entry": [
                    "enters at 8 am and leaves at 12 pm",
                    "starts at 8 am and ends at 12 pm",
                ],
                "late_entry": [
                    "enters at 12 pm and leaves at 4 pm",
                    "starts at noon and ends at 4 pm",
                ],
            },
            "transportation_between_home_and_daycare": {
                "walking": [
                    "we go walking",
                    "we arrive walking",
                    "we return walking",
                ],
                "car": [
                    "we go by car",
                    "we arrive by car",
                    "we return by car",
                ],
                "school_bus": [
                    "we go by school bus",
                    "we arrive by school bus",
                    "we return by school bus",
                ],
                "public_transport": [
                    "we go by public transport",
                    "we arrive by public transport",
                    "we return by public transport",
                ],
            },
            "activity": {
                "activity_type": {
                    "therapy": [
                        "therapy",
                        "occupational therapy",
                        "physical therapy",
                        "speech therapy",
                        "psychotherapy",
                    ],
                    "extracurricular": [
                        "workshop",
                        "art class",
                        "music",
                        "dance",
                        "painting",
                        "crafts",
                    ],
                    "sport": [
                        "sport",
                        "swimming",
                        "soccer",
                        "karate",
                        "gymnastics",
                        "cycling",
                    ],
                    "park": [
                        "park",
                        "playground",
                        "going to the park",
                        "playing outside",
                    ],
                    "family": [
                        "grandparents’ house",
                        "visiting family",
                        "family time",
                        "at cousins’ house",
                    ],
                    "other": [
                        "other activity",
                        "free activity",
                        "visit",
                        "outing",
                    ],
                },
                "repetition_pattern": {
                    "every_day": ["every day", "daily"],
                    "monday_to_friday": ["monday to friday", "weekdays"],
                    "weekend": ["saturday and/or sunday", "weekend"],
                    "several_days": ["several days per week", "two or three times a week"],
                    "once_a_week": ["once a week", "one time per week"],
                },
                "days": {
                    "monday": ["monday"],
                    "tuesday": ["tuesday"],
                    "wednesday": ["wednesday"],
                    "thursday": ["thursday"],
                    "friday": ["friday"],
                    "saturday": ["saturday"],
                    "sunday": ["sunday"],
                },
                "schedule": {
                    "start_time": [
                        "the activity starts at",
                        "starts at",
                        "from",
                    ],
                    "end_time": [
                        "the activity ends at",
                        "ends at",
                        "until",
                    ],
                },
            },
            "sleep_environment": {
                "own_room": [
                    "sleeps in his own room",
                    "has his own room",
                    "private room",
                ],
                "shared_room_brother": [
                    "shares room with brother",
                    "shares room with sister",
                    "sleeps with brothers",
                    "sleeps with sisters",
                ],
                "shared_with_father": [
                    "sleeps with parents",
                    "sleeps with mom and dad",
                    "sleeps in parents’ bed",
                    "sleeps in bed with parents",
                ],
            },
            "enviroment_conditions": {
                "air_conditioning": [
                    "has air conditioning",
                    "uses air conditioning",
                    "there is air conditioning",
                ],
                "heating": [
                    "has heating",
                    "uses heating",
                    "there is heating",
                ],
                "humidifier": [
                    "has humidifier",
                    "uses humidifier",
                    "there is humidifier",
                ],
                "deshumidifier": [
                    "has dehumidifier",
                    "uses dehumidifier",
                    "there is dehumidifier",
                ],
                "air_purifier": [
                    "has air purifier",
                    "uses air purifier",
                    "there is air purifier",
                ],
                "fan": [
                    "has fan",
                    "uses fan",
                    "there is fan",
                ],
                "none": [
                    "has no climate devices",
                    "does not use climate devices",
                    "no climate devices available",
                ],
            },
        }
    }
}
