KEYWORDS_FAMILY_CONTEXT_PT = {
    "family context and environment": {
        "0_84": {
            "family_members": {
                "mother": [
                    "mora com a mãe",
                    "mora com a mamãe",
                    "vive com a mãe",
                    "mora com sua mãezinha",
                ],
                "father": [
                    "mora com o pai",
                    "mora com o papai",
                    "vive com o pai",
                    "mora com seu paizinho",
                ],
                "both_parents": [
                    "mora com ambos os pais",
                    "vive com os dois pais",
                ],
                "brothers": [
                    "mora com seus irmãos",
                    "mora com suas irmãs",
                    "tem irmãos",
                    "tem irmãs",
                    "tem um irmão",
                    "tem uma irmã",
                ],
                "grandparents": [
                    "mora com seus avós",
                    "mora com o avô",
                    "mora com a avó",
                    "tem avós",
                    "tem um avô",
                    "tem uma avó",
                    "mora com os avós",
                ],
                "others_family_members": [
                    "mora com tios",
                    "mora com tias",
                    "mora com o tio",
                    "mora com a tia",
                    "mora com primos",
                    "mora com primas",
                    "mora com o primo",
                    "mora com a prima",
                    "mora com outros familiares",
                ],
                "caregivers": [
                    "mora com cuidador",
                    "mora com cuidadora",
                    "tem um cuidador",
                    "tem uma cuidadora",
                ],
                "others": [
                    "mora com outras pessoas",
                    "mora com alguém mais",
                    "mora com outra pessoa",
                ],
            },
            "more_than_one_home": {
                "different_homes": [
                    "mais de uma casa",
                    "várias casas",
                    "lares diferentes",
                    "casas distintas",
                    "casa da mãe e do pai",
                    "vive em duas casas",
                    "às vezes com a mãe",
                    "às vezes com o pai",
                ],
                "One_home": [
                    "uma única casa",
                    "uma casa",
                    "um lar",
                    "vive em uma casa",
                    "vive com os pais",
                    "vive com a mãe e o pai",
                    "lar único",
                    "lar estável",
                    "casa estável",
                    "casa única",
                    "lar com ambos os pais",
                    "vive com ambos os pais",
                    "vive com os dois pais",
                ],
            },
            "home_schedule": {
                "fixed_days": [
                    "dias fixos",
                    "dias estabelecidos",
                ],
                "altern_weekends": [
                    "fins de semana alternados",
                    "fins de semana diferentes",
                    "fins de semana rotativos",
                    "um fim de semana com a mãe e outro com o pai",
                    "um fim de semana com o pai e outro com a mãe",
                    "fins de semana com cada pai",
                    "fins de semana com cada um",
                ],
                "weekly_rotations": [
                    "rotação semanal",
                    "semanas alternadas",
                    "semanas diferentes",
                    "semanas variáveis",
                    "uma semana com a mãe e outra com o pai",
                    "uma semana com o pai e outra com a mãe",
                    "semanas com cada pai",
                    "semanas com cada um",
                ],
                "other_schedule": [
                    "outro tipo de horário",
                    "horário diferente",
                ],
            },
            "principal_caregiver": {
                "mother": [
                    "a mãe é a cuidadora principal",
                    "a mãe cuida do bebê",
                    "a mãe é a principal cuidadora",
                    "a mãe cuida da criança",
                    "a mãe é responsável pelo cuidado",
                ],
                "father": [
                    "o pai é o cuidador principal",
                    "o pai cuida do bebê",
                    "o pai é o principal cuidador",
                    "o pai cuida da criança",
                    "o pai é responsável pelo cuidado",
                ],
                "both_parents": [
                    "ambos os pais são os cuidadores principais",
                    "a mãe e o pai cuidam do bebê",
                    "os dois pais cuidam da criança",
                    "os pais são responsáveis pelo cuidado",
                ],
                "granny_and_grandpa": [
                    "os avós são os cuidadores principais",
                    "os avós cuidam do bebê",
                    "os avós cuidam da criança",
                    "os avós são responsáveis pelo cuidado",
                ],
                "granny": [
                    "a avó é a cuidadora principal",
                    "a avó cuida do bebê",
                    "a avó cuida da criança",
                    "a avó é responsável pelo cuidado",
                ],
                "grandpa": [
                    "o avô é o cuidador principal",
                    "o avô cuida do bebê",
                    "o avô cuida da criança",
                    "o avô é responsável pelo cuidado",
                ],
                "caregiver": [
                    "o cuidador é o cuidador principal",
                    "o cuidador cuida do bebê",
                    "o cuidador cuida da criança",
                    "o cuidador é responsável pelo cuidado",
                ],
            },
            "go_to_daycare": {
                "no": [
                    "não vai à creche",
                    "não frequenta creche",
                    "não está na creche",
                    "não vai ao jardim de infância",
                    "não frequenta o jardim de infância",
                    "não está no jardim de infância",
                    "não vai à escola infantil",
                    "não frequenta a escola infantil",
                    "não está na escola infantil",
                ],
                "kindergarden": [
                    "vai à creche",
                    "frequenta creche",
                    "está na creche",
                    "vai ao jardim de infância",
                    "frequenta o jardim de infância",
                    "está no jardim de infância",
                    "vai à escola infantil",
                    "frequenta a escola infantil",
                    "está na escola infantil",
                ],
                "school": [
                    "vai à escola",
                    "frequenta a escola",
                    "está na escola",
                    "vai ao colégio",
                    "frequenta o colégio",
                    "está no colégio",
                ],
            },
            "days_of_attendance": {
                "monday": [
                    "segunda-feira na creche",
                    "frequenta às segundas-feiras",
                    "vai às segundas-feiras",
                ],
                "tuesday": [
                    "terça-feira na creche",
                    "frequenta às terças-feiras",
                    "vai às terças-feiras",
                ],
                "wednesday": [
                    "quarta-feira na creche",
                    "frequenta às quartas-feiras",
                    "vai às quartas-feiras",
                ],
                "thursday": [
                    "quinta-feira na creche",
                    "frequenta às quintas-feiras",
                    "vai às quintas-feiras",
                ],
                "friday": [
                    "sexta-feira na creche",
                    "frequenta às sextas-feiras",
                    "vai às sextas-feiras",
                ],
            },
            "attendance_schedule": {
                "morning": [
                    "frequenta de manhã",
                    "vai de manhã",
                    "horário matutino",
                    "turno da manhã",
                ],
                "afternoon": [
                    "frequenta à tarde",
                    "vai à tarde",
                    "horário vespertino",
                    "turno da tarde",
                ],
                "full_day": [
                    "frequenta o dia todo",
                    "vai o dia todo",
                    "horário integral",
                    "turno completo",
                ],
            },
            "entry_time": {
                "early_entry": [
                    "entra às 8h e sai às 12h",
                    "entra às oito e sai ao meio-dia",
                ],
                "late_entry": [
                    "entra às 12h e sai às 16h",
                    "entra ao meio-dia e sai às quatro",
                ],
            },
            "transportation_between_home_and_daycare": {
                "walking": [
                    "vamos a pé",
                    "chegamos a pé",
                    "voltamos a pé",
                ],
                "car": [
                    "vamos de carro",
                    "chegamos de carro",
                    "voltamos de carro",
                ],
                "school_bus": [
                    "vamos de ônibus escolar",
                    "chegamos de ônibus escolar",
                    "voltamos de ônibus escolar",
                ],
                "public_transport": [
                    "vamos de transporte público",
                    "chegamos de transporte público",
                    "voltamos de transporte público",
                ],
            },
            "activity": {
                "activity_type": {
                    "therapy": [
                        "terapia",
                        "terapia ocupacional",
                        "fisioterapia",
                        "fonoaudiologia",
                        "psicoterapia",
                    ],
                    "extracurricular": [
                        "oficina",
                        "aula de arte",
                        "música",
                        "dança",
                        "pintura",
                        "artesanato",
                    ],
                    "sport": [
                        "esporte",
                        "natação",
                        "futebol",
                        "caratê",
                        "ginástica",
                        "bicicleta",
                    ],
                    "park": [
                        "parque",
                        "praça",
                        "sair ao parque",
                        "brincar fora",
                    ],
                    "family": [
                        "casa dos avós",
                        "visita à família",
                        "tempo com a família",
                        "na casa dos primos",
                    ],
                    "other": [
                        "outra atividade",
                        "atividade livre",
                        "visita",
                        "passeio",
                    ],
                },
                "repetition_pattern": {
                    "every_day": ["todos os dias", "diariamente"],
                    "monday_to_friday": ["segunda a sexta", "dias de semana"],
                    "weekend": ["sábado e/ou domingo", "fim de semana"],
                    "several_days": ["vários dias por semana", "duas ou três vezes por semana"],
                    "once_a_week": ["uma vez por semana", "uma vez na semana"],
                },
                "days": {
                    "monday": ["segunda-feira"],
                    "tuesday": ["terça-feira"],
                    "wednesday": ["quarta-feira"],
                    "thursday": ["quinta-feira"],
                    "friday": ["sexta-feira"],
                    "saturday": ["sábado"],
                    "sunday": ["domingo"],
                },
                "schedule": {
                    "start_time": ["a atividade começa às", "começa às", "a partir das"],
                    "end_time": ["a atividade termina às", "termina às", "até às"],
                },
            },
            "sleep_environment": {
                "own_room": [
                    "dorme em seu próprio quarto",
                    "tem seu próprio quarto",
                    "quarto individual",
                ],
                "shared_room_brother": [
                    "divide o quarto com o irmão",
                    "divide o quarto com a irmã",
                    "dorme com os irmãos",
                    "dorme com as irmãs",
                ],
                "shared_with_father": [
                    "dorme com os pais",
                    "dorme com a mãe e o pai",
                    "dorme na cama dos pais",
                    "dorme na cama com os pais",
                ],
            },
            "enviroment_conditions": {
                "air_conditioning": [
                    "tem ar-condicionado",
                    "usa ar-condicionado",
                    "há ar-condicionado",
                ],
                "heating": [
                    "tem aquecimento",
                    "usa aquecimento",
                    "há aquecimento",
                ],
                "humidifier": [
                    "tem umidificador",
                    "usa umidificador",
                    "há umidificador",
                ],
                "deshumidifier": [
                    "tem desumidificador",
                    "usa desumidificador",
                    "há desumidificador",
                ],
                "air_purifier": [
                    "tem purificador de ar",
                    "usa purificador de ar",
                    "há purificador de ar",
                ],
                "fan": [
                    "tem ventilador",
                    "usa ventilador",
                    "há ventilador",
                ],
                "none": [
                    "não tem aparelhos de clima",
                    "não usa aparelhos de clima",
                    "não há aparelhos de clima",
                ],
            },
        }
    }
}
